version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongonetwork
    ports:
      - "27017:27017"

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongonetwork:27017/newDB
